version: '3.1'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app